[package]
name = "host"
version = "0.1.0"
edition = "2024"

[features]
default = ["use-compiled-tools"]
use-installed-tools = ["spirv-builder/use-installed-tools"]
use-compiled-tools = ["spirv-builder/use-compiled-tools"]

[dependencies]
shared = { path = "../shared" }
rtx-bench = { path = "../rtx-bench" }
rtx-prim = { path = "../rtx-prim" }
rtx-obj = { path = "../rtx-obj" }
rtx-mat = { path = "../rtx-mat" }
rtx-tex = { path = "../rtx-tex" }

log = { workspace = true }
env_logger = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
ouroboros = { workspace = true }
futures = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true }
image = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
toml = { workspace = true }

[build-dependencies]
spirv-builder = { workspace = true }

[lints]
workspace = true
